const data = {
  myQuotes: [
    {
      quote_id: 25,
      imdb_id: "tt0104761",
      quote: "Jag kan visst cykla, tänk för att jag kan det ni! I smyg!",
      created_at: "2025-09-25 11:26",
      updated_at: null,
      media_title: "Lotta på Bråkmakargatan",
      like_count: 2,
      has_liked: true,
      actor: {
        id: 82326,
        name: "Grete Havnesköld",
        profile_path: "/vQxqvksMEPW5PpfZ8ONswn6mwJ7.jpg",
        appears_in: [],
      },
      character_name: "Lotta",
    },
    {
      quote_id: 30,
      imdb_id: "tt0075314",
      quote: "You talking to me?",
      created_at: "2025-09-29 08:27",
      updated_at: null,
      media_title: "Taxi Driver",
      like_count: 0,
      has_liked: false,
      actor: null,
      character_name: null,
    },
    {
      quote_id: 18,
      imdb_id: "tt0081590",
      quote: "Jag var nykter i morse men nu börjar det ordna upp sig.",
      created_at: "2025-09-24 13:57",
      updated_at: "2025-09-25 11:11",
      media_title: "Sällskapsresan",
      like_count: 3,
      has_liked: true,
      actor: {
        id: 79058,
        name: "Sven Melander",
        profile_path: "/yCppWZXXtYrI2tj4qwKBGNPwkEN.jpg",
        appears_in: [],
      },
      character_name: "Berra Ohlsson",
    },
    {
      quote_id: 29,
      imdb_id: "tt0086250",
      quote: "Say hello to my little friend!",
      created_at: "2025-09-25 14:20",
      updated_at: "2025-09-25 14:21",
      media_title: "Scarface",
      like_count: 7,
      has_liked: false,
      actor: {
        id: 1158,
        name: "Al Pacino",
        profile_path: "/cCECRgy3E1e1jE6y5xtSsThnLid.jpg",
        appears_in: [],
      },
      character_name: "Tony Montana",
    },
  ],
  myMedia: [
    {
      imdb_id: "tt0103064",
      media_type: "Movie",
      title: "Avatar",
      overview:
        "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
      poster_path: "/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
      backdrop_path: "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
      release_date: "2009-12-15",
      tagline: "Enter the world of Pandora.",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 3.8,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Vacker men lite tråkig",
        content: "James Cameron gör det igen.",
        cmdb_score: 1,
        contribution_date: "2024-10-22",
      },
      genres: [
        { id: 14, name: "Fantasy" },
        { id: 28, name: "Action" },
        { id: 878, name: "Science Fiction" },
      ],
      top_actors: [
        {
          id: 65731,
          name: "Sam Worthington",
          character: "Jake Sully",
          profile_path: "/mflBcox36s9ZPbsZPVOuhf6axaJ.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 8691,
          name: "Zoe Saldaña",
          character: "Neytiri",
          profile_path: "/iOVbUH20il632nj2v01NCtYYeSg.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 10205,
          name: "Sigourney Weaver",
          character: "Dr. Grace Augustine",
          profile_path: "/wTSnfktNBLd6kwQxgvkqYw6vEon.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0103064",
      media_type: "Movie",
      title: "Terminator 2: Judgment Day",
      overview:
        "Set ten years after the events of the original, James Camerons classic sci-fi action flick tells the story of a second attempt to get the rid of rebellion leader John Connor, this time targeting the boy himself. However, the rebellion has sent a reprogrammed terminator to protect Connor.",
      poster_path: "/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
      backdrop_path: "/vINgGecnz95iDL6fjQMARDsocgG.jpg",
      release_date: "1991-07-03",
      tagline: "Its nothing personal.",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 4.6,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Läskig och spännande",
        content: "James Cameron och Arnold i perfekt symbios.",
        cmdb_score: 5,
        contribution_date: "2024-10-21",
      },
      genres: [
        { id: 28, name: "Action" },
        { id: 53, name: "Thriller" },
        { id: 878, name: "Science Fiction" },
      ],
      top_actors: [
        {
          id: 1100,
          name: "Arnold Schwarzenegger",
          character: "The Terminator",
          profile_path: "/z6IbTtI2FWAVZE6b1V4mqEHjwO6.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 2713,
          name: "Linda Hamilton",
          character: "Sarah Connor",
          profile_path: "/7FNn9Z5xkRS9EFbGL2tpmpph9xV.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 820,
          name: "Edward Furlong",
          character: "John Connor",
          profile_path: "/e221dMIBgb6Lk092GIkHB9ohQF1.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0071807",
      media_type: "Movie",
      title: "Mannen med den gyllene pistolen",
      overview:
        'Scaramanga är världens bäste och högst betalde lönnmördare. Han tar en miljon dollar per uppdrag. När en kula av rent guld med "007" ingraverat upptäcks, blir det en jakt på liv och död när Bond ger sig efter Scaramanga - som samtidigt jagar Bond. En sak kommer att bli avgörande i duellen mellan de båda, den gyllene pistolen.',
      poster_path: "/fXkdvJCYIoW1G27Ca3dyrNpTOFd.jpg",
      backdrop_path: "/3tpNEbRahT8smy7RraaWa0xg9Gv.jpg",
      release_date: "1974-12-04",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 4,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Spännande klassiker!",
        content: "Det här var en riktigt underhållande klassiker.",
        cmdb_score: 4,
        contribution_date: "2025-09-24",
      },
      genres: [
        { id: 12, name: "Äventyr" },
        { id: 28, name: "Action" },
        { id: 53, name: "Thriller" },
      ],
      top_actors: [
        {
          id: 10222,
          name: "Roger Moore",
          character: "James Bond",
          profile_path: "/anMuX2HBIMvLUZm7A6yuKSqiJxP.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 113,
          name: "Christopher Lee",
          character: "Francisco Scaramanga",
          profile_path: "/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 10341,
          name: "Britt Ekland",
          character: "Mary Goodnight",
          profile_path: "/xwqKmseMHCXwLQGxardWgPTtAcW.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0060196",
      media_type: "Movie",
      title: "A Million Ways to Die in the West",
      overview:
        "As a cowardly farmer begins to fall for the mysterious new woman in town, he must put his new-found courage to the test when her husband, a notorious gun-slinger, announces his arrival.",
      poster_path: "/n9SicwnoNGWBwE75le27sUhCLMm.jpg",
      backdrop_path: "/zJRVO9G5c7tTfDRvfC13nUDqXdH.jpg",
      release_date: "2014-05-22",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 3.6,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Ganska rolig stundtals",
        content:
          "Filmen överraskar av och till med att vara svinrolig...sedan lite trist.",
        cmdb_score: 4,
        contribution_date: "2024-10-04",
      },
      genres: [
        { id: 35, name: "Comedy" },
        { id: 37, name: "Western" },
      ],
      top_actors: [
        {
          id: 52139,
          name: "Seth MacFarlane",
          character: "Albert",
          profile_path: "/8oQJqM51Z0Qtdb7sE6ZfX1peNCB.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 6885,
          name: "Charlize Theron",
          character: "Anna",
          profile_path: "/ie1KbeYFG5E0GVr1QP7tDNuXvga.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 71070,
          name: "Amanda Seyfried",
          character: "Louise",
          profile_path: "/gtBUIpZ3dvLpOMIVORxE6sHSyZj.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0060196",
      media_type: "Movie",
      title: "The Good, the Bad and the Ugly",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      backdrop_path: "/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg",
      release_date: "1966-12-22",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 4.5,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Bra klassiker som står sig",
        content: "Denna film är en äkta western som står sig än idag.",
        cmdb_score: 4,
        contribution_date: "2024-10-11",
      },
      genres: [{ id: 37, name: "Western" }],
      top_actors: [
        {
          id: 190,
          name: "Clint Eastwood",
          character: "Blondie",
          profile_path: "/dU35NnjZ4aGw5abIJe3WXVf3Eey.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 3265,
          name: "Eli Wallach",
          character: "Tuco Ramirez",
          profile_path: "/s452wxFLaOwAIs6juD0rrvxaFxL.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 4078,
          name: "Lee Van Cleef",
          character: "Sentenza / Angel Eyes",
          profile_path: "/yQc5wjNCdRZzPp5E2wRPRYsEq9a.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0081590",
      media_type: "Movie",
      title: "Sällskapsresan",
      overview:
        "Stig-Helmer and Ole Bramserud on a trip to the Canary Islands for Christmas.",
      poster_path: "/9773l2A4n7k6OL5e6aalZveckOl.jpg",
      backdrop_path: "/i4ZwZdt7nUNI7ovrbzvbGqkZpgf.jpg",
      release_date: "1980-08-22",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 4.2,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Bra klassiker som står sig",
        content:
          "Denna film är en riktig kultklassiker som faktiskt står sig än idag.",
        cmdb_score: 5,
        contribution_date: "2024-10-15",
      },
      genres: [{ id: 35, name: "Comedy" }],
      top_actors: [
        {
          id: 79056,
          name: "Lasse Åberg",
          character: "Stig-Helmer Olsson",
          profile_path: "/8D2fcrW7xYptC8a3ELhkUNx3Tvw.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 79057,
          name: "Jon Skolmen",
          character: "Ole Bramserud",
          profile_path: "/ozKFKbZpbVTc2kTEJsWLII5Whs5.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 79060,
          name: "Lottie Ejebrant",
          character: "Maj-Britt 'Majsan' Lindberg",
          profile_path: "/osMdApPQIM8thXifjH9XczGq2Nx.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0100405",
      media_type: "Movie",
      title: "Pretty Woman",
      overview:
        "While on a business trip in Los Angeles, Edward Lewis, a millionaire entrepreneur who makes a living buying and breaking up companies, picks up a prostitute, Vivian, while asking for directions; after, Edward hires Vivian to stay with him for the weekend to accompany him to a few social events, and the two get closer only to discover there are significant hurdles to overcome as they try to bridge the gap between their very different worlds.",
      poster_path: "/hVHUfT801LQATGd26VPzhorIYza.jpg",
      backdrop_path: "/3tuWpnCTe14zZZPt6sI1W9ByOXx.jpg",
      release_date: "1990-03-23",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 3.9,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Inte min kopp the",
        content: "Overkligt och konstig återgivning av prostitution.",
        cmdb_score: 2,
        contribution_date: "2024-10-01",
      },
      genres: [
        { id: 35, name: "Comedy" },
        { id: 10749, name: "Romance" },
      ],
      top_actors: [
        {
          id: 1205,
          name: "Richard Gere",
          character: "Edward Lewis",
          profile_path: "/i7wcBNmFldh2E4QInCvmv7CPSIR.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 1204,
          name: "Julia Roberts",
          character: "Vivian Ward",
          profile_path: "/imKO3GakmeaZwrmGTEjtYSV5qeb.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 1206,
          name: "Jason Alexander",
          character: "Philip Stuckey",
          profile_path: "/qRezZ2yhM2bmBERt7jVcxo8RVSA.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0099348",
      media_type: "Movie",
      title: "Dances with Wolves",
      overview:
        "Wounded Civil War soldier John Dunbar tries to commit suicide—and becomes a hero instead. As a reward, he's assigned to his dream post, a remote junction on the Western frontier, and soon makes unlikely friends with the local Sioux tribe.",
      tagline: "Inside everyone is a frontier waiting to be discovered.",
      poster_path: "/cvaBVpS0GzKqBd63pFT8f1E8OKv.jpg",
      backdrop_path: "/ywWva4trKw7f3wtbz81Fe3FnrtC.jpg",
      release_date: "1990-03-30",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 3.9,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Ske ma eller ske ma däns först",
        content:
          "Episk, känslosam film om vänskap och kulturkrockar, med fantastisk regi och skådespeleri av Kevin Costner.",
        cmdb_score: 4,
        contribution_date: "2024-10-17",
      },
      genres: [
        { id: 18, name: "Drama" },
        { id: 37, name: "Western" },
      ],
      top_actors: [
        {
          id: 1269,
          name: "Kevin Costner",
          character: "Lieutenant Dunbar",
          profile_path: "/bykmxJHLfbFM3NT05RZXhx8YTzF.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 1581,
          name: "Mary McDonnell",
          character: "Stands With A Fist",
          profile_path: "/qqdaaFLEPXbB8thVJJkYJ4WoAuj.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 6804,
          name: "Graham Greene",
          character: "Kicking Bird",
          profile_path: "/ubX9pwrzQqnR41gAGyY1GoSZr1G.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0413573",
      media_type: "TVSeries",
      title: "Grey's Anatomy",
      overview:
        "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
      tagline: "Begin again.",
      poster_path: "/jcEl8SISNfGdlQFwLzeEtsjDvpw.jpg",
      backdrop_path: "/nmg2lY4QuyXQrAnrC2lRblK5rT6.jpg",
      release_date: "null",
      first_air_date: "2005-03-27",
      last_air_date: "2024-05-30",
      cmdb_score: 3,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Tat lungt syster",
        content: "Mycket hångel och död blir det på sjukhuset...huvva!",
        cmdb_score: -1,
        contribution_date: "2024-10-11",
      },
      genres: [
        { id: 18, name: "Drama" },
        { id: 99999, name: "Hospital" },
      ],
      top_actors: [
        {
          id: 9280,
          name: "Ellen Pompeo",
          character: "Meredith Grey",
          profile_path: "/3v4MY2ZEGN2UYQOWsBSOKTY0AEa.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 171075,
          name: "Chandra Wilson",
          character: "Miranda Bailey",
          profile_path: "/bsrrhxZgHlvQ8vkvtSOU2YNgd0g.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 25544,
          name: "James Pickens Jr.",
          character: "Richard Webber",
          profile_path: "/8z4GaJeshPUAOa642aPkiJz3R3d.jpg",
          order: 3,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0108778",
      media_type: "TVSeries",
      title: "Friends",
      overview:
        "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
      tagline: "I'll be there for you.",
      poster_path: "/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg",
      backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
      release_date: "null",
      first_air_date: "1994-09-22",
      last_air_date: "2004-05-06",
      cmdb_score: 3,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Soffan gick sönder",
        content: "Bra serie fram till soffan gick sönder... då fick jag nog",
        cmdb_score: 5,
        contribution_date: "2024-10-01",
      },
      genres: [{ id: 35, name: "Comedy" }],
      top_actors: [
        {
          id: 4491,
          name: "Jennifer Aniston",
          character: "Rachel Green",
          profile_path: "/qPXG41rYdUGldZhMhuZFvmpZKRp.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 14405,
          name: "Courteney Cox",
          character: "Monica Geller",
          profile_path: "/ezQfLRpq2NbNPwnEd4zFvofeJ3V.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 14408,
          name: "Matthew Perry",
          character: "Chandler Bing",
          profile_path: "/ecDzkLWPV1z0x31I1GTjNmLxAHk.jpg",
          order: 4,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0944947",
      media_type: "TVSeries",
      title: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      tagline: "Winter is coming.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      release_date: "null",
      first_air_date: "2011-04-17",
      last_air_date: "2019-05-19",
      cmdb_score: 4,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Vintern kom till slut",
        content:
          "Bra serie fram till sista säsongen... Om bara författaren kunde slutat hoppa studsmatta och skrivit färdigt sista boken så kunde nog serien fått ett mer värdigt slut.",
        cmdb_score: 1,
        contribution_date: "2024-10-06",
      },
      genres: [
        { id: 18, name: "Drama" },
        { id: 10759, name: "Action & Adventure" },
        { id: 14, name: "Fantasy" },
      ],
      top_actors: [
        {
          id: 22970,
          name: "Peter Dinklage",
          character: "Tyrion 'The Halfman' Lannister",
          profile_path: "/9CAd7wr8QZyIN0E7nm8v1B6WkGn.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 239019,
          name: "Kit Harington",
          character: "Jon Snow",
          profile_path: "/htGBMno71BJAEGF3Y9f62MdA3Yt.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 12795,
          name: "Nikolaj Coster-Waldau",
          character: "Sir Jaime 'Kingslayer' Lannister",
          profile_path: "/rpFOERbHkj7GWxkinUNiQ76sSGk.jpg",
          order: 5,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0411008",
      media_type: "TVSeries",
      title: "Lost",
      overview:
        "Stripped of everything, the survivors of a horrific plane crash  must work together to stay alive. But the island holds many secrets.",
      tagline: "Everything happens for a reason.",
      poster_path: "/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg",
      backdrop_path: "/yUOFocKDW7MCC5isx4FK8A68QFp.jpg",
      release_date: "null",
      first_air_date: "2004-09-22",
      last_air_date: "2010-05-23",
      cmdb_score: 4.2,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "4, 8, 15, 16, 23, 42",
        content: "Bunkern och dess filurer är bara så roliga.",
        cmdb_score: 1,
        contribution_date: "2024-09-16",
      },
      genres: [
        { id: 18, name: "Drama" },
        { id: 10759, name: "Action & Adventure" },
        { id: 14, name: "Fantasy" },
      ],
      top_actors: [
        {
          id: 28657,
          name: "Matthew Fox",
          character: "Jack Shephard",
          profile_path: "/ynb8OvZI4tkoPyovbmtm3HxwvUV.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 19034,
          name: "Evangeline Lilly",
          character: "Kate Austen",
          profile_path: "/pJHX2jd7ytre3NQbF9nlyWUqxH3.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 12646,
          name: "Terry O'Quinn",
          character: "John Locke",
          profile_path: "/kSweOGPprLe1vDvu38wJQaWIih7.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0095016",
      media_type: "Movie",
      title: "Die Hard",
      overview:
        "NYPD cop John McClane's plan to reconcile with his estranged wife is thrown for a serious loop when, minutes after he arrives at her office, the entire building is overtaken by a group of terrorists. With little help from the LAPD, wisecracking McClane sets out to single-handedly rescue the hostages and bring the bad guys down.",
      tagline:
        "Twelve terrorists. One cop. The odds are against John McClane... That's just the way he likes it.",
      poster_path: "/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg",
      backdrop_path: "/rahJyvdMruvqUmSLWRQKYS57mx8.jpg",
      release_date: "1988-07-15",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 1.5,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Bruce Willis när han är som bäst",
        content:
          "Denna film var det bästa som Byvägen 120 hade att erbjuda 1994 när en ung herr Lundgren var hemma sjuk från skolan. Kanske att dagen höjdes lite med rostmackor och lite för hastigt ihoprörd Oboy med klumpar i. Jag har nog sett filmen 20 gånger och varje gång blir den lite bättre. Yippee-ki-yay på er!",
        cmdb_score: 2,
        contribution_date: "2024-09-16",
      },
      genres: [{ id: 28, name: "Action" }],
      top_actors: [
        {
          id: 62,
          name: "Bruce Willis",
          character: "John McClane",
          profile_path: "/w3aXr1e7gQCn8MSp1vW4sXHn99P.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 4566,
          name: "Alan Rickman",
          character: "Hans Gruber",
          profile_path: "/nKl8ZRYjBJya7aj7phJUyrtSll6.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 7674,
          name: "Alexander Godunov",
          character: "Karl",
          profile_path: "/4oBCz83Pjxe66PlTmA9ph7m5O0e.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0125439",
      media_type: "Movie",
      title: "Notting Hill",
      overview:
        "William Thacker is a London bookstore owner whose humdrum existence is thrown into romantic turmoil when famous American actress Anna Scott appears in his shop. A chance encounter over spilled orange juice leads to a kiss that blossoms into a full-blown affair. As the average bloke and glamorous movie star draw closer and closer together, they struggle to reconcile their radically different lifestyles in the name of love.",
      tagline:
        "Can the most famous film star in the world fall for the man on the street?",
      poster_path: "/hHRIf2XHeQMbyRb3HUx19SF5Ujw.jpg",
      backdrop_path: "/enTZhfxAdgOCdFdbj52MR3F10yC.jpg",
      release_date: "1999-05-21",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 5,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "kärlek",
        content: "det är alltid härligt med en romantisk kommedi.",
        cmdb_score: 5,
        contribution_date: "2024-10-02",
      },
      genres: [
        { id: 10749, name: "Romance" },
        { id: 35, name: "Comedy" },
      ],
      top_actors: [
        {
          id: 1204,
          name: "Julia Roberts",
          character: "Anna Scott",
          profile_path: "/imKO3GakmeaZwrmGTEjtYSV5qeb.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 3291,
          name: "Hugh Grant",
          character: "William Thacker",
          profile_path: "/hsSfxSHzkKJ6ZKq1Ofngcp7aAnT.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 18022,
          name: "Gina McKee",
          character: "Bella",
          profile_path: "/rHL7GGeFZ2x9PbFL2P3hVkLfvAS.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0109686",
      media_type: "Movie",
      title: "Dumb and Dumber",
      overview:
        'Lloyd and Harry are two men whose stupidity is really indescribable. When Mary, a beautiful woman, loses an important suitcase with money before she leaves for Aspen, the two friends (who have found the suitcase) decide to return it to her. After some "adventures" they finally get to Aspen where, using the lost money they live it up and fight for Mary\'s heart.',
      tagline: "For Harry and Lloyd, every day is a no-brainer.",
      poster_path: "/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg",
      backdrop_path: "/riDYJYk4g8YnDjEgYOSSKzWTldq.jpg",
      release_date: "1994-12-16",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 5,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "and you totally redeem yourself",
        content: "Den här filmen är omöjlig att inte älska.",
        cmdb_score: 5,
        contribution_date: "2024-10-02",
      },
      genres: [{ id: 35, name: "Comedy" }],
      top_actors: [
        {
          id: 206,
          name: "Jim Carrey",
          character: "Lloyd Christmas",
          profile_path: "/u0AqTz6Y7GHPCHINS01P7gPvDSb.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 8447,
          name: "Jeff Daniels",
          character: "Harry Dunne",
          profile_path: "/cMQb76YP0BcO9xzHUwz4yCIK8GO.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 34485,
          name: "Lauren Holly",
          character: "Mary Swanson",
          profile_path: "/bWQsB6ueNNkygxCiIxyKznQAiOK.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt0120689",
      media_type: "Movie",
      title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      tagline:
        "Paul Edgecomb didn't believe in miracles. Until the day he met one.",
      poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
      backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
      release_date: "1999-12-10",
      first_air_date: null,
      last_air_date: null,
      cmdb_score: 4,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "För lång",
        content:
          "Filmen är en stark berättelse och den är sevärd. Men den är lite för lång för att få full pott.",
        cmdb_score: 4,
        contribution_date: "2024-10-03",
      },
      genres: [
        { id: 80, name: "Crime" },
        { id: 14, name: "Fantasy" },
        { id: 18, name: "Drama" },
      ],
      top_actors: [
        {
          id: 31,
          name: "Tom Hanks",
          character: "Paul Edgecomb",
          profile_path: "/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 52,
          name: "David Morse",
          character: "Brutus 'Brutal' Howell",
          profile_path: "/A6zGbkFjM3uajIakgsSeNTmSKqY.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 5149,
          name: "Bonnie Hunt",
          character: "Jan Edgecomb",
          profile_path: "/tT9C6uLztgN8OxJULq6F9iEzqlA.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
    {
      imdb_id: "tt16288804",
      media_type: "TVSeries",
      title: "Berlin",
      overview:
        "During his glory days, Berlin and a gang assembled in Paris for one of his greatest plans ever: stealing 44 million euros' worth of jewels in one night.",
      tagline:
        "Only two things can brighten a dark day: The first is love. The second is stealing a fortune.",
      poster_path: "/69YuvoiWTtK6oyYH2Jl4Q6SgZ59.jpg",
      backdrop_path: "/179sUCj5AcFKdQpvDhkIX15NRgy.jpg",
      release_date: null,
      first_air_date: "2023-12-29",
      last_air_date: "2023-12-29",
      cmdb_score: 5,
      contribution: {
        has_reviewed: true,
        has_rated: false,
        title: "Mästerlig",
        content:
          "En serie man både älskar och hatar. Det har finess, samtidigt som den är plump.",
        cmdb_score: 5,
        contribution_date: "2024-08-21",
      },
      genres: [
        { id: 80, name: "Crime" },
        { id: 10759, name: "Action & Adventure" },
        { id: 18, name: "Drama" },
      ],
      top_actors: [
        {
          id: 1109836,
          name: "Pedro Alonso",
          character: "Andrés 'Berlín' de Fonollosa",
          profile_path: "/38HeVKeOBztVYrLJOWzAtEZiB02.jpg",
          order: 0,
          primary_role: "Acting",
        },
        {
          id: 114463,
          name: "Michelle Jenner",
          character: "Keila",
          profile_path: "/g3JyHqwBcV7g1ds3dHtWkDXyXqb.jpg",
          order: 1,
          primary_role: "Acting",
        },
        {
          id: 16441,
          name: "Tristán Ulloa",
          character: "Damián Vázquez",
          profile_path: "/sglKcvdU3e8hTy1kOghEbT0GdHS.jpg",
          order: 2,
          primary_role: "Acting",
        },
      ],
    },
  ],
};
